packages:
  - packages/*
  - apps/*
  - demo/*

allowBuilds:
  esbuild: false
  node-hid: false
  spawn-sync: false
  unrs-resolver: false
  usb: false

catalog:
  '@tanstack/query-core': 5.99.0
  lru-cache: 11.3.5
  '@tanstack/react-query': 5.99.0
  '@ton/core': 0.63.1
  '@ton/crypto': 3.3.0
  '@tonconnect/protocol': 2.5.0-alpha.0
  '@tonconnect/sdk': 3.5.0-alpha.0
  '@tonconnect/ui': 2.5.0-alpha.0
  '@tonconnect/ui-react': 2.5.0-alpha.0
  '@types/react': 19.2.3
  '@types/react-dom': 19.2.3
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.81.5

catalogs:
  react-native:
    '@types/react': 19.2.14
    '@types/react-dom': 19.1.0
    react: 19.1.0
    react-dom: 19.1.0
    react-native: 0.81.5

onlyBuiltDependencies:
  - node-hid
