packages:
  - packages/*
  - apps/*
  - demo/*

allowBuilds:
  '@reown/appkit': false
  bufferutil: false
  core-js-pure: false
  esbuild: false
  keccak: false
  node-hid: false
  spawn-sync: false
  unrs-resolver: false
  usb: false
  utf-8-validate: false

catalog:
  '@tanstack/query-core': ^5.100.14
  '@tanstack/react-query': ^5.101.0
  '@ton/core': ^0.63.1
  '@ton/crypto': ^3.3.0
  '@tonconnect/bridge-sdk': ^0.2.8
  '@tonconnect/protocol': ^3.0.0
  '@tonconnect/sdk': ^4.0.0
  '@tonconnect/ui': ^3.0.0
  '@tonconnect/ui-react': ^3.0.0
  '@types/react': 19.2.3
  '@types/react-dom': 19.2.3
  buffer: ^6.0.3
  eslint: 9.39.4
  lru-cache: ^11.5.1
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.81.5
  rimraf: 6.1.3
  typescript: 5.9.3
  vite: 8.0.14

minimumReleaseAgeExclude:
  - '@tonconnect/protocol@3.0.0'
  - '@tonconnect/sdk@4.0.0'
  - '@tonconnect/ui-react@3.0.0'
  - '@tonconnect/ui@3.0.0'
  - '@truecarry/vite-plugin-web-extension@4.5.3'

onlyBuiltDependencies:
  - node-hid
